#!/bin/bash

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS='@im=fcitx'
export DefaultIMModule=fcitx
export WALLPAPER="$HOME/Pictures/.wallpapers"

xset s off -dpms &
xsetroot -cursor_name left-ptr &
xrandr --output DP-2 --auto --output DP-4 --right-of DP-2 --output HDMI-0 --right-of DP-4 &
nitrogen --restore &

xbindkeys &
xset r rate 180 50 &
xmodmap -e "keycode 11 = 2 quotedbl" &
xmodmap -e "keycode 47 = semicolon apostrophe" &
xmodmap -e "keycode 48 = colon at" &
fcitx &

conky -c ~/.conkyrc -d &
conky -c ~/.conkyclockrc -d &
~/.restartconky &

dunst -config ~/.dunstrc &
dropbox &

picom -b --unredir-if-possible &

exec i3
