#!/bin/bash
set -eu
cd $(dirname $0)

declare -r fzfbase="$HOME/.fzf"
declare -r fzf="https://github.com/junegunn/fzf"

install() {
    local force=$1
    [[ "$force" == "true" ]] && rm -Rf "$fzfbase"
    [[ -d $fzfbase ]] && echo "skipped fzf installation" || \
    (git clone $fzf $fzfbase && $fzfbase/install)
    return $?
}

declare force_opt="false"
while getopts f OPT; do
    case $OPT in
    "f")
        force_opt="true" ;;
    esac
done

install $force_opt
