#!/bin/bash
set -eu
cd $(dirname $0)

declare -r tpm="https://github.com/tmux-plugins/tpm"
declare -r tpmbase="$HOME/.tmux/plugins/tpm"

install() {
    local force=$1
    mkdir -p $(dirname $tpmbase)
    [[ "$force" == "true" ]] && rm -Rf "$tpmbase"
    [[ -d $tpmbase ]] && echo "skipped tpm installation" || \
    (git clone $tpm $tpmbase)
    return $?
}

declare force_opt="false"
while getopts f OPT; do
    case $OPT in
    "f")
        force_opt="true" ;;
    esac
done

install $force_opt
