#!/bin/bash
set -eu
cd $(dirname $0)

export ZPLUG_HOME="$HOME/.zsh/zplug"
declare -r zplug="https://github.com/zplug/zplug"

get() {
    local force=$1
    [[ "$force" == "true" ]] && rm -Rf "$ZPLUG_HOME/*"
    git clone $zplug $ZPLUG_HOME
    return $?
}

declare force_opt="false"
while getopts f OPT; do
    case $OPT in
    "f")
        force_opt="true" ;;
    esac
done

get $force_opt
