#!/bin/bash
cd $(dirname $0)

declare -r base="$HOME/.zsh/plugin"
declare -a plugins=()
plugins+=("zsh-users/zaw")
plugins+=("zsh-users/zsh-syntax-highlighting")
plugins+=("zsh-users/zsh-completions")
plugins+=("zsh-users/zsh-autosuggestions")

get() {
    local force=$1
    [[ "$force" == "true" ]] && rm -Rf "$base/*"
    mkdir -p $base
    for plugin in ${plugins[@]}; do
        [[ -d $(basename $plugin) ]] && echo "skipped $plugin" || \
        git clone "https://github.com/${plugin}" $base/$(basename $plugin)
    done
}

declare force_opt="false"
while getopts f OPT; do
    case $OPT in
    "f")
        force_opt="true" ;;
    esac
done

get $force_opt
