# vim: ft=tmux
set -g pane-border-style "fg=#494d64"
set -g pane-active-border-style "fg=#8aadf4"
set -g pane-border-format "#{?pane_active,#[bold,fg=#cad3f5],#[fg=#8087a2]}#{pane_index}:#{pane_current_command}#[default]"
set -g copy-mode-match-style "fg=#24273a,bg=#f5a97f"
set -g copy-mode-current-match-style "fg=#24273a,bg=#eed49f"
set -g mode-style "fg=#24273a,bg=#eed49f"
set -g message-style "fg=#cad3f5,bg=#1e2030"
set -g message-command-style "fg=#24273a,bg=#8aadf4"
