# vim: ft=tmux
set -g pane-border-style "fg=#45475a"
set -g pane-active-border-style "fg=#89b4fa"
set -g pane-border-format "#{?pane_active,#[bold,fg=#cdd6f4],#[fg=#7f849c]}#{pane_index}:#{pane_current_command}#[default]"
set -g copy-mode-match-style "fg=#1e1e2e,bg=#fab387"
set -g copy-mode-current-match-style "fg=#1e1e2e,bg=#f9e2af"
set -g mode-style "fg=#1e1e2e,bg=#f9e2af"
set -g message-style "fg=#cdd6f4,bg=#181825"
set -g message-command-style "fg=#1e1e2e,bg=#89b4fa"
