# vim: ft=tmux
set -g pane-border-style "fg=#51576d"
set -g pane-active-border-style "fg=#8caaee"
set -g pane-border-format "#{?pane_active,#[bold,fg=#c6d0f5],#[fg=#838ba7]}#{pane_index}:#{pane_current_command}#[default]"
set -g copy-mode-match-style "fg=#303446,bg=#ef9f76"
set -g copy-mode-current-match-style "fg=#303446,bg=#e5c890"
set -g mode-style "fg=#303446,bg=#e5c890"
set -g message-style "fg=#c6d0f5,bg=#292c3c"
set -g message-command-style "fg=#303446,bg=#8caaee"
