# vim: ft=tmux
bar="#[default,fg=#6e738d]|#[default]"
hostname="#[bold,fg=#cad3f5]#H#[default]"
session="#[bold,fg=#8aadf4]#S#[default]"
cpu="#($HOME/.tmux/scripts/cpu.sh)"
mem="#($HOME/.tmux/scripts/mem.sh)"
user="#($HOME/.tmux/scripts/user.sh)"
ipv4="#($HOME/.tmux/scripts/ipv4.sh)"
ipv6="#($HOME/.tmux/scripts/ipv6.sh)"

set -g status-position bottom
set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-bg "#1e2030"
set -g status-fg "#cad3f5"
set -g status-left-length 40
set -g status-right-length 140
set -g status-left " [$session] "
set -g status-right "$bar C: $cpu $bar M: $mem $bar U: $user $bar I: $ipv4, $ipv6 $bar $hostname $bar %Y-%m-%d %H:%M:%S"
set -wg window-status-format "#[fg=#8087a2] #I:#W #[default]$bar"
set -wg window-status-current-format "#[bold,fg=#24273a,bg=#8aadf4] #I:#W#{?window_bell_flag,!,}#{?window_zoomed_flag,Z,} #[default]$bar"
