" 256色ターミナルを使用する
set t_CO=256
set background=dark

" エンコーディング
set encoding=utf-8
set fileencoding=utf-8

" 行番号を表示させる
set number
set cursorline

" 自動インデント
set autoindent
set smartindent

" タブ幅
set tabstop=4
set shiftwidth=4

" Deleteではn文字削除
set backspace=2

" タブをスペースに変換
"set expandtab

" ESCキーの変更
inoremap <silent> jj <ESC>

" カーソル後の文字を削除
inoremap <silent> <C-d> <Del>

" 行頭復帰と行末回帰のキー変更
noremap 0 $
noremap 1 0

" カーソルから行頭までを削除
" カーソルから行末までを削除
inoremap <silent> <C-d>1 <ESC>lc^
inoremap <silent> <C-d>0 <ESC>lc$

" カーソルから行頭までをヤンク
" カーソルから行末までをヤンク
inoremap <silent> <C-y>1 <Esc>ly0<Insert>
inoremap <silent> <C-y>0 <Esc>ly$<Insert>

" タブの作り方と切り替え方
noremap <silent><S-Tab> :tabnew<CR>
noremap <Tab><Tab> gT

" シンタックスハイライトは重いので消す
autocmd ColorScheme * highlight LineNr ctermfg=244 ctermbg=NONE
autocmd ColorScheme * highlight CursorLineNr term=bold ctermfg=220 ctermbg=NONE
colorscheme solarized
