local map = vim.keymap.set

map("n", ";;", "<cmd>tabnew<cr>", { desc = "New tab" })
map("n", "<S-l>", "<cmd>tabnext<cr>", { desc = "Next tab" })
map("n", "<S-h>", "<cmd>tabprevious<cr>", { desc = "Previous tab" })
map("n", "<C-l>", "<cmd>nohlsearch<cr>", { desc = "Clear search highlight" })
map("x", "p", [["_dP]], { desc = "Paste without yanking replaced text" })

map("n", "-", function()
	require("oil").open()
end, { desc = "Open parent directory" })
map("n", "<C-w>-", "<cmd>split<cr>", { desc = "Horizontal split" })
map("n", "<C-w>|", "<cmd>vsplit<cr>", { desc = "Vertical split" })

map("n", "<leader>f", function()
	require("fzf-lua").files()
end, { desc = "Find files" })
map("n", "<leader>g", function()
	require("fzf-lua").git_files()
end, { desc = "Find git files" })
map("n", "<leader>G", function()
	require("fzf-lua").git_status()
end, { desc = "Git status" })
map("n", "<leader>b", function()
	require("fzf-lua").buffers()
end, { desc = "Buffers" })
map("n", "<leader>h", function()
	require("fzf-lua").oldfiles()
end, { desc = "Recent files" })
map("n", "<leader>r", function()
	require("fzf-lua").live_grep()
end, { desc = "Live grep" })

map({ "n", "v" }, "<C-a>", "<cmd>CodeCompanionActions<cr>", { desc = "CodeCompanion actions" })
map({ "n", "v" }, "<localleader>a", "<cmd>CodeCompanionChat Toggle<cr>", { desc = "Toggle CodeCompanion chat" })
map("n", "<localleader>c", "<cmd>CodeCompanionCLI<cr>", { desc = "Open CodeCompanion CLI" })
map("v", "ga", "<cmd>CodeCompanionChat Add<cr>", { desc = "Add selection to CodeCompanion chat" })
