if whence -p tmux > /dev/null; then
    if [[ -z "$TMUX" ]]; then
        count=$(tmux list-session 2> /dev/null | wc -l)
        if tmux has-session 2> /dev/null; then
            echo "Choose one of the tmux sessions below"
            tmux list-session
            echo "c: Create new tmux session"
            echo "n: Without tmux"
            echo -n "(default=c): "
            read choose
            case "$choose" in
            "c")
                exec tmux new-session ;;
            "n")
                ;;
            "")
                exec tmux new-session ;;
            *)
                exec tmux attach-session -t "$choose" ;;
            esac
        else
            echo "c: Create new tmux session"
            echo "n: Without tmux"
            echo -n "(default=c): "
            read choose
            case "$choose" in
            "n" )
                ;;
            * )
                exec tmux new-session ;;
            esac
        fi
    fi
fi
