#!/bin/bash

(( $EUID > 0 )) && sudo $0 $@ && exit 0

if [[ -f /etc/lsb-release ]]; then
  DIST=$(grep DISTRIB_ID /etc/lsb-release | cut -d '=' -f 2)
elif [[ -f /etc/debian_version ]]; then
  DIST=Debian
fi

case $DIST in
  Ubuntu|Debian)
    sudo apt-get update \
      && apt-get install -y software-properties-common \
      && add-apt-repository ppa:neovim-ppa/unstable \
      && apt-get update \
      && DEBIAN_FRONTEND=noninteractive \
         apt-get install -y neovim
      ;;
  *)
    exit 127
    ;;
esac

