git:
  pagers:
    - name: delta
      pager: 'delta --features=catppuccin-mocha --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"'
    - {}
