::() {
  local session="$1"
  if [[ -z ${session} ]]
  then
    tmux
  elif [[ -n $(tmux ls -F "#{session_name}" | \grep -x "${session}") ]]
  then
    tmux attach -t "${session}"
  else
    tmux $@
  fi
}
