set -g prefix C-t
unbind C-b

set -g default-terminal "screen-256color"
set -g base-index 1
set -qg history-limit 10000000
set -sg escape-time 0
set -sa terminal-overrides ",*256col*:Ss=\\E[%p1%d q:Se=\\E[1 q"

# Catppuccin flavour selection. Uncomment exactly one line.
# set -g @theme "catppuccin-latte"
# set -g @theme "catppuccin-frappe"
# set -g @theme "catppuccin-macchiato"
set -g @theme "catppuccin-mocha"

if -F '#{==:#{@theme},catppuccin-latte}' "source-file $HOME/dotfiles/etc/tmux/tmux/themes/catppuccin-latte.conf"
if -F '#{==:#{@theme},catppuccin-frappe}' "source-file $HOME/dotfiles/etc/tmux/tmux/themes/catppuccin-frappe.conf"
if -F '#{==:#{@theme},catppuccin-macchiato}' "source-file $HOME/dotfiles/etc/tmux/tmux/themes/catppuccin-macchiato.conf"
if -F '#{==:#{@theme},catppuccin-mocha}' "source-file $HOME/dotfiles/etc/tmux/tmux/themes/catppuccin-mocha.conf"

## https://stackoverflow.com/questions/32374907/tmux-mouse-copy-mode-jumps-to-bottom
set -g mouse on
unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi y send-keys -X copy-pipe-no-clear "pbcopy" \; send-keys -X clear-selection

bind c new-window -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r Z resize-pane -Z

bind a set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"
bind r source-file $HOME/.tmux.conf\; display "configuration reloaded"
unbind R

source-file $HOME/.tmux/statusbar.conf
