---
use_default_settings:
  engines:
    keep_only:
      - bing
      - mwmbl
      - duckduckgo

search:
  autocomplete: ""
  formats:
    - html
    - json

outgoing:
  request_timeout: 6.0
  max_request_timeout: 8.0
  retries: 0
  pool_connections: 4
  pool_maxsize: 4

engines:
  - name: yahoo japan
    engine: xpath
    shortcut: yjp
    search_url: "https://search.yahoo.co.jp/search?p={query}"
    results_xpath: //ol/li[a[starts-with(@href, 'http')]]
    url_xpath: ./a[1]/@href
    title_xpath: ./a
    content_xpath: ./div
    headers:
      User-Agent: Mozilla/5.0
      Accept-Language: ja-JP,ja;q=0.9
    categories: general
    disabled: true
  - name: bing
    disabled: true
  - name: mwmbl
    disabled: true
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    ddg_url: http://ddg-proxy:8081/html/
    enable_http: true
    disabled: true
