#!/bin/bash

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS='@im=fcitx'
export DefaultIMModule=fcitx
export WALLPAPER="$HOME/Pictures/.wallpapers"

## comptoggle
CONKYRC=$HOME/.conkyrc
if [[ -e $CONKYRC ]]; then
    sed -i -e "s/own_window yes/own_window no/g" $CONKYRC
fi

## Wallpaper
${WALLPAPER}/ctrl.sh &

xset s off -dpms

xbindkeys &
xset r rate 180 50
xmodmap -e "keycode 11 = 2 quotedbl"
xmodmap -e "keycode 47 = semicolon apostrophe"
xmodmap -e "keycode 48 = colon at"
fcitx &
dunst -config ~/.dunstrc &
mate-volume-control-applet &
mate-screensaver &
xsetroot -cursor_name left-ptr &
xrandr --output VGA-1 --left-of DP-2 --output DP-2 --primary &
conky -d &
compton -b --unredir-if-possible --config $HOME/.config/compton/compton.conf &
dropbox start -i &

exec i3
# DISPLAY=:0.0 i3 &
# DISPLAY=:0.1 i3
