#!/bin/bash

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS='@im=fcitx'
export DefaultIMModule=fcitx
export WALLPAPER="$HOME/Pictures/.wallpapers"

## comptoggle
CONKYRC=$HOME/.conkyrc
if [[ -e $CONKYRC ]]; then
    sed -i -e "s/own_window yes/own_window no/g" $CONKYRC
fi

xset s off -dpms

xbindkeys &
xset r rate 180 50
xmodmap -e "keycode 11 = 2 quotedbl"
xmodmap -e "keycode 47 = semicolon apostrophe"
xmodmap -e "keycode 48 = colon at"
fcitx &
dunst -config ~/.dunstrc &
xsetroot -cursor_name left-ptr &
xrandr --output HDMI-1 --rotate left --left-of HDMI-3 --output HDMI-3 --auto --primary
conky -c .conkyclockrc -d

## Wallpaper
nitrogen --restore &

synergyc 131.112.21.31

exec i3
