# vim: ft=tmux
if -F '#{==:#{@theme},forest}' "source-file $HOME/dotfiles/etc/hosts/macos/tmux/tmux/themes/forest.conf"
if -F '#{==:#{@theme},gruvbox}' "source-file $HOME/dotfiles/etc/hosts/macos/tmux/tmux/themes/gruvbox.conf"
