# vim: ft=tmux
bar="#[default,fg=#6e738d]|#[default]"
cpu="#($HOME/.tmux/scripts/cpu.sh)"
mem="#($HOME/.tmux/scripts/mem.sh)"
ssd="#($HOME/.tmux/scripts/ssd.sh)"
ipv4="#($HOME/.tmux/scripts/ipv4.sh)"
ipv6="#($HOME/.tmux/scripts/ipv6.sh)"
session="#[bold,fg=#8aadf4]#S#[default]"
hostname="#[bold,fg=#cad3f5]#H#[default]"

set -g status-position bottom
set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-bg "#1e2030"
set -g status-fg "#cad3f5"
set -g status-left-length 40
set -g status-right-length 160
set -g status-left " [$session] "
set -g status-right "$bar #[fg=#a6da95]#[default]  $cpu $bar #[fg=#8bd5ca]#[default]  $mem $bar #[fg=#f5a97f]#[default] $ssd $bar #[fg=#91d7e3]#[default] $ipv4, $ipv6 $bar #[fg=#b7bdf8]󰌢#[default]  $hostname $bar #[fg=#eed49f]#[default]  %Y-%m-%d %H:%M:%S"
set -wg window-status-separator ""
set -wg window-status-format "#[fg=#8087a2] #I:#W #[default]$bar"
set -wg window-status-current-format "#[bold,fg=#24273a,bg=#8aadf4] #I:#W#{?window_bell_flag,!,}#{?window_zoomed_flag,Z,} #[default]$bar"
