# vim: ft=tmux
bar="#[default,fg=#9ca0b0]|#[default]"
cpu="#($HOME/.tmux/scripts/cpu.sh)"
mem="#($HOME/.tmux/scripts/mem.sh)"
ssd="#($HOME/.tmux/scripts/ssd.sh)"
ipv4="#($HOME/.tmux/scripts/ipv4.sh)"
ipv6="#($HOME/.tmux/scripts/ipv6.sh)"
session="#[bold,fg=#1e66f5]#S#[default]"
hostname="#[bold,fg=#4c4f69]#H#[default]"

set -g status-position bottom
set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-bg "#e6e9ef"
set -g status-fg "#4c4f69"
set -g status-left-length 40
set -g status-right-length 160
set -g status-left " [$session] "
set -g status-right "$bar #[fg=#40a02b]#[default] $cpu $bar #[fg=#179299]#[default] $mem $bar #[fg=#fe640b]#[default] $ssd $bar #[fg=#04a5e5]#[default] $ipv4, $ipv6 $bar #[fg=#7287fd]󰌢#[default] $hostname $bar #[fg=#df8e1d]#[default] %Y-%m-%d %H:%M:%S"
set -wg window-status-separator ""
set -wg window-status-format "#[fg=#8c8fa1] #I:#W #[default]$bar"
set -wg window-status-current-format "#[bold,fg=#eff1f5,bg=#1e66f5] #I:#W#{?window_bell_flag,!,}#{?window_zoomed_flag,Z,} #[default]$bar"
