# vim: ft=tmux
bar="#[default,fg=#737994]|#[default]"
cpu="#($HOME/.tmux/scripts/cpu.sh)"
mem="#($HOME/.tmux/scripts/mem.sh)"
ssd="#($HOME/.tmux/scripts/ssd.sh)"
ipv4="#($HOME/.tmux/scripts/ipv4.sh)"
ipv6="#($HOME/.tmux/scripts/ipv6.sh)"
session="#[bold,fg=#8caaee]#S#[default]"
hostname="#[bold,fg=#c6d0f5]#H#[default]"

set -g status-position bottom
set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-bg "#292c3c"
set -g status-fg "#c6d0f5"
set -g status-left-length 40
set -g status-right-length 160
set -g status-left " [$session] "
set -g status-right "$bar #[fg=#a6d189]#[default] $cpu $bar #[fg=#81c8be]#[default] $mem $bar #[fg=#ef9f76]#[default] $ssd $bar #[fg=#99d1db]#[default] $ipv4, $ipv6 $bar #[fg=#babbf1]󰌢#[default] $hostname $bar #[fg=#e5c890]#[default] %Y-%m-%d %H:%M:%S"
set -wg window-status-separator ""
set -wg window-status-format "#[fg=#838ba7] #I:#W #[default]$bar"
set -wg window-status-current-format "#[bold,fg=#303446,bg=#8caaee] #I:#W#{?window_bell_flag,!,}#{?window_zoomed_flag,Z,} #[default]$bar"
