# vim: ft=tmux
bar="#[default,fg=#6c7086]|#[default]"
cpu="#($HOME/.tmux/scripts/cpu.sh)"
mem="#($HOME/.tmux/scripts/mem.sh)"
ssd="#($HOME/.tmux/scripts/ssd.sh)"
ipv4="#($HOME/.tmux/scripts/ipv4.sh)"
ipv6="#($HOME/.tmux/scripts/ipv6.sh)"
session="#[bold,fg=#89b4fa]#S#[default]"
hostname="#[bold,fg=#cdd6f4]#H#[default]"

set -g status-position bottom
set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-bg "#181825"
set -g status-fg "#cdd6f4"
set -g status-left-length 40
set -g status-right-length 160
set -g status-left " [$session] "
set -g status-right "$bar #[fg=#a6e3a1]#[default] $cpu $bar #[fg=#94e2d5]#[default] $mem $bar #[fg=#fab387]#[default] $ssd $bar #[fg=#89dceb]#[default] $ipv4, $ipv6 $bar #[fg=#b4befe]󰌢#[default] $hostname $bar #[fg=#f9e2af]#[default] %Y-%m-%d %H:%M:%S"
set -wg window-status-separator ""
set -wg window-status-format "#[fg=#7f849c] #I:#W #[default]$bar"
set -wg window-status-current-format "#[bold,fg=#1e1e2e,bg=#89b4fa] #I:#W#{?window_bell_flag,!,}#{?window_zoomed_flag,Z,} #[default]$bar"
