# vim: ft=tmux
bar="#[default,fg=#665c54]|#[default]"
cpu="#($HOME/.tmux/scripts/cpu.sh)"
mem="#($HOME/.tmux/scripts/mem.sh)"
ssd="#($HOME/.tmux/scripts/ssd.sh)"
ipv4="#($HOME/.tmux/scripts/ipv4.sh)"
ipv6="#($HOME/.tmux/scripts/ipv6.sh)"
session="#[bold,fg=#fabd2f]#S#[default]"
hostname="#[bold,fg=#ebdbb2]#H#[default]"

set -g status-position bottom
set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-bg "#282828"
set -g status-fg "#ebdbb2"
set -g status-left-length 40
set -g status-right-length 140
set -g status-left "[$session] "
set -g status-right "$bar #[fg=#d79921]#[default]  $cpu $bar #[fg=#98971a]#[default]  $mem $bar #[fg=#458588]#[default] $ssd $bar #[fg=#83a598]#[default] $ipv4, $ipv6 $bar 󰌢  $hostname $bar #[fg=#a89984]#[default]  %Y-%m-%d %H:%M:%S"
set -wg window-status-format "#[fg=#928374]#I:#W $bar"
set -wg window-status-current-format "#[bold,fg=#1d2021,bg=#d79921] #I:#W*#{?window_bell_flag,!,}#{?window_zoomed_flag,Z,} #[default]$bar"
