if $(whereis tmux > /dev/null 2>&1); then
	if [ -z "$TMUX" ]; then
		tmux list-session > /dev/null 2>&1 | wc -l | awk '{print $0}' | read count

		if $(tmux has-session > /dev/null 2>&1); then
			echo "Choose one of the tmux sessions below"
			tmux list-session
			echo "c: Create new tmux session"
			echo "n: Without tmux"
			echo -n "(default=0): "
			read choose
			
			case "$choose" in
				"c" )
					exec tmux new-session
					;;
				"w" )
					;;
				"" )
					exec tmux attach-session -t 0
					;;
				* )
					exec tmux attach-session -t "$choose"
					;;
			esac
		else
			echo "c: Create new tmux session"
			echo "n: Without tmux"
			echo -n "(default=c): "
			read choose

			case "$choose" in
				"n" )
					;;
				* )
					exec tmux new-session
					;;
			esac
		fi
	fi
fi
