"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 750
scan_timeout = 50

format = """
$directory\
$git_branch\
$git_metrics\
$git_status\
$hostname\
$cmd_duration\
$line_break\
$python\
$aws\
$character"""
right_format = """$status$jobs$time$battery"""

[directory]
format = "[$path]($style)"
style = "blue"
truncate_to_repo = false
truncation_length = 0
fish_style_pwd_dir_length = 0
read_only = ""

[git_branch]
format = "[ $symbol$branch]($style)"
style = "bright-black"
symbol = " "

[git_status]
format = "[ $all_status$ahead_behind]($style)"
style = "bright-black"
conflicted = "*"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = ""
untracked = "*"
stashed = "≡"
modified = "*"
staged = "+"
renamed = "»"
deleted = "✘"
typechanged = "*"
ignore_submodules = true

[git_metrics]
disabled = false
format = "([ +$added]($added_style))([ -$deleted]($deleted_style))"
added_style = "green"
deleted_style = "red"
ignore_submodules = true

[cmd_duration]
min_time = 5000
format = "[ $duration]($style)"
style = "yellow"
show_milliseconds = false

[status]
disabled = false
format = "[$symbol$status]($style) "
symbol = "✘ "
style = "red"
map_symbol = true
recognize_signal_code = true

[jobs]
symbol = "✦ "
style = "bright-black"
number_threshold = 1
symbol_threshold = 1

[time]
disabled = false
format = "[$time]($style) "
style = "bright-black"
time_format = "%H:%M"

[battery]
disabled = false
format = "[$symbol$percentage]($style) "
full_symbol = "• "
charging_symbol = "↑ "
discharging_symbol = "↓ "
unknown_symbol = "? "
empty_symbol = "! "

[line_break]
disabled = false

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold purple)"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
symbol = ""
detect_extensions = []
detect_files = []
detect_folders = []
python_binary = "python3"

[aws]
format = "[$profile]($style) "
style = "yellow"
symbol = ""

[kubernetes]
disabled = true

[container]
disabled = true

[hostname]
ssh_only = true
format = "[ $hostname]($style)"
style = "bright-black"
trim_at = "."

[username]
disabled = true
