#trap "echo -e '\n'; return 0" 2
#if whence -p tmux 1> /dev/null && [[ -z ${TMUX} ]]; then
#  if tmux has-session 2> /dev/null; then
#    echo "Hello, would you like to continue with an existing session or start a new one?"
#    tmux list-sessions
#  else
#    echo "Hello, would you like to start a new session?"
#  fi
#  echo "c: create new session"
#  echo "n: without tmux"
#  echo -n "> "
#  read opt
#  case ${opt} in
#    c|) exec tmux new-session ;;
#    n) echo ;;
#    *) exec tmux attach-session -t ${opt} ;;
#  esac
#fi
