export CARGO_HOME="$HOME/.cargo"
export GOPATH="$HOME/io/gocode"

typeset -U path PATH
path=(
  "$HOME/bin"
  "$HOME/dotfiles/bin"
  "$HOME/io/bin"
  "$HOME/.local/bin"
  "$HOME/.nix-profile/bin"
  /run/current-system/sw/bin
  /nix/var/nix/profiles/default/bin
  "$CARGO_HOME/bin"
  "$GOPATH/bin"
  /opt/homebrew/bin
  /opt/homebrew/sbin
  /usr/local/bin
  /usr/local/sbin
  /usr/bin
  /usr/sbin
  /bin
  /sbin
  /snap/bin
  /Library/Apple/usr/bin
  $path
)
