HISTFILE="$HOME/.zhistory"
HISTSIZE=10000
SAVEHIST=10000
setopt APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY
setopt NO_BEEP

bindkey -e
autoload -Uz compinit
compinit

alias ..='cd ..'
alias ...='cd ../..'
alias ll='ls -la'
alias la='ls -A'

if (( $+commands[mise] )); then
  eval "$(mise activate zsh)"
fi

if (( $+commands[direnv] )); then
  eval "$(direnv hook zsh)"
fi

# Match Fish's bold Catppuccin Mocha lavender directory style.
PROMPT='%B%F{#b4befe}%~%f%b%# '
unset RPROMPT
