export CARGO_HOME="$HOME/.cargo"
export DENO_INSTALL="$HOME/.deno"
export GOPATH="$HOME/io/gocode"

typeset volta_home="$HOME/.volta"
if [[ "$OSTYPE" == darwin* && "$MACHTYPE" == x86_64-* ]]; then
  volta_home="$HOME/.volta_x64"
fi
export VOLTA_HOME="$volta_home"

typeset -U path PATH
path=(
  "$HOME/bin"
  "$HOME/dotfiles/bin"
  "$HOME/io/bin"
  "$HOME/.local/bin"
  "$HOME/.nix-profile/bin"
  /run/current-system/sw/bin
  /nix/var/nix/profiles/default/bin
  "$DENO_INSTALL/bin"
  "$CARGO_HOME/bin"
  "$GOPATH/bin"
  "$VOLTA_HOME/bin"
  /opt/homebrew/bin
  /opt/homebrew/sbin
  /usr/local/bin
  /usr/local/sbin
  /usr/bin
  /usr/sbin
  /bin
  /sbin
  /snap/bin
  /Library/Apple/usr/bin
  $path
)
unset volta_home

HISTFILE="$HOME/.zhistory"
HISTSIZE=10000
SAVEHIST=10000
setopt APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY
setopt NO_BEEP

bindkey -e
autoload -Uz compinit
compinit

alias ..='cd ..'
alias ...='cd ../..'
alias ll='ls -la'
alias la='ls -A'

if (( $+commands[mise] )); then
  eval "$(mise activate zsh)"
fi

if (( $+commands[direnv] )); then
  eval "$(direnv hook zsh)"
fi

# Match Fish's bold Catppuccin Mocha lavender directory style.
PROMPT='%B%F{#b4befe}%~%f%b%# '
unset RPROMPT
