if [[ -d "$HOME/.zsh/conf.d" ]]; then
    for conf in $(find -L ~/.zsh/conf.d/ -name "*.zsh" | sort); do
        source $conf
    done
fi

# automatically added by fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
