##
# 一般設定
##
bindkey -e					# Emacsバインド
autoload -U compinit		# 補完機能をロード
compinit -u
HISTSIZE=10000				# 10000行の履歴を記録
SAAVEHIST=10000
HISTFILE=$HOME/.zhistory	# ヒストリファイルの指定


##
# オプション設定
##
setopt ALWAYS_TO_END		# 補完時にカーソルを末尾に移動させる
setopt NO_BEEP				# 端末ベルを使用しない
setopt AUTO_CD				# ディレクトリ名で移動
setopt AUTOPUSHD			# cdするときpushdする
setopt PUSHD_IGNORE_DUPS	# 同じディレクトリはpushdしない
setopt CORRECT				# コマンドの入力ミスを指摘させる
setopt CORRECT_ALL			# 全引数に修正を加えさせる
setopt MAGIC_EQUAL_SUBST	# =以降も補完させる
setopt PROMPT_SUBST			# プロンプトで変数拡張 コマンド置換 計算拡張を実行
setopt NOTIFY				# バックグラウンドジョブの状態を通知する
setopt AUTO_LIST			# 曖昧入力時にリストを表示する
setopt AUTO_MENU			# 
setopt LIST_PACKED			# 補完候補をなるべく短く表示
setopt LIST_TYPES			# 補完候補を種類別表示する
setopt NO_LIST_BEEP			# 曖昧補完時にビープ音を鳴らさない
setopt IGNORE_EOF			# <C-d>でログアウトしない
setopt BANG_HIST			# cshのヒストリ拡張を使う
setopt HIST_IGNORE_DUPS		# 重複するコマンドを記憶しない
setopt HIST_IGNORE_ALL_DUPS	# 重複するコマンドが来たら古いものを削除
setopt HIST_IGNORE_SPACE	# 先頭スペースは記憶しない
setopt HIST_REDUCE_BLANKS	# 空白は削除して記憶
setopt SHARE_HISTORY		# 履歴の共有


##
# 補完フォーマット追加
##
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'


##
# パス
##
export PATH=$PATH:/usr/local/vpnserver:$HOME/bin
##
# COLFG256で256色指定できるようにする
# colortest()で確認できる
##
for X in {16..255}; do
	COLFG256[${X}]=$(echo "\e[38;5;${X}m")
	COLBG256[${X}]=$(echo "\e[48;5;${X}m")
done
unset X
COL_DEF="$(echo '\e[0m')"
COL_BOLD="$(echo '\e[1m')"

function colortest {
	for c in {000..255}; do
		echo -n "\e[38;5;${c}m $c"
		[ $(($c%16)) -eq 15 ] && echo
	done
	echo
}


##
# lsや補完の色設定
##
export CLICOLOR=true
export LSCOLORS=Exfxcxdxbxegedabagacad	
export LS_COLORS='di=01;34:ln=01;35:so=01;32:ex=01;31:bd=40;33:cd=40;33:su=41;30:sg=46;30:tw=42;30:ow=43;30'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
autoload -U colors; colors


##
# シンタックスハイライトを使う
##
if [ -f ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
	source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi


##
# プロンプト
##
blue1=${COLFG256[069]}
blue2=${COLFG256[075]}
blue3=${COLFG256[045]}
green1=${COLFG256[034]}
green2=${COLFG256[036]}

PROMPT='${blue1}[%B${blue2}%n%b${blue1}@%M:${blue3}%~${blue1}]%f %B${green1}[Pi]%f%b
%# '


##
# デフォルトで色を付ける
##
alias grep="grep -n --color=auto"

function man() {
    env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
    man "$@"
}


##
# ショートカット
##
alias :q="exit"
alias sss="source ~/.zshrc"
alias lg="cd /var/log"
alias l="ls"
alias ll="ls -l"
alias la="ls -alr"
alias df="df -h"
alias cl="clear"
alias x="startx"
alias ls="ls --color=auto"
alias open="spacefm > /dev/null 2>&1 &"lias ::="tmux"


##
# lsしたらcdする
##
function cd() {
	builtin cd $1 && ls
}

