# vim: ft=tmux

set -g status-position bottom
set -g status "on"
set -g status-interval 5
set -g status-justify "left"
set -g status-left-length 0
set -g status-right-length 200

set -g @catppuccin_status_cpu_local "#[fg=#{E:@thm_yellow}]#[fg=#{E:@thm_crust},bg=#{E:@thm_yellow}]  #[fg=#{E:@thm_fg},bg=#{E:@thm_surface_1}] #($HOME/.tmux/scripts/cpu.sh)#[fg=#{E:@thm_surface_1}] "
set -g @catppuccin_status_ram_local "#[fg=#{E:@thm_teal}]#[fg=#{E:@thm_crust},bg=#{E:@thm_teal}]  #[fg=#{E:@thm_fg},bg=#{E:@thm_surface_1}] #($HOME/.tmux/scripts/mem.sh)#[fg=#{E:@thm_surface_1}] "
set -g @catppuccin_status_storage "#[fg=#{E:@thm_peach}]#[fg=#{E:@thm_crust},bg=#{E:@thm_peach}]󰋊 #[fg=#{E:@thm_fg},bg=#{E:@thm_surface_1}] #($HOME/.tmux/scripts/storage.sh)#[fg=#{E:@thm_surface_1}] "
set -g @catppuccin_status_battery_local "#[fg=#{E:@thm_lavender}]#[fg=#{E:@thm_crust},bg=#{E:@thm_lavender}]#($HOME/.tmux/scripts/battery-icon.sh) #[fg=#{E:@thm_fg},bg=#{E:@thm_surface_1}] #($HOME/.tmux/scripts/battery.sh)#[fg=#{E:@thm_surface_1}] "
set -g @catppuccin_status_host "#[fg=#{E:@thm_mauve}]#[fg=#{E:@thm_crust},bg=#{E:@thm_mauve}]󰌢  #[fg=#{E:@thm_fg},bg=#{E:@thm_surface_1}] #H#[fg=#{E:@thm_surface_1}] "
set -g @catppuccin_application_text " #{USER}"

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_cpu_local}"
set -ag status-right "#{E:@catppuccin_status_ram_local}"
set -ag status-right "#{E:@catppuccin_status_storage}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -ag status-right "#{E:@catppuccin_status_battery_local}"
set -ag status-right "#{E:@catppuccin_status_host}"

set -g message-style "fg=#{E:@thm_crust},bg=#{E:@thm_lavender},align=left,width=100%"
set -g message-command-style "fg=#{E:@thm_crust},bg=#{E:@thm_lavender},align=left,width=100%"
