# See: https://github.com/marketplace/actions/publish-docker

name: GitHub CI/CD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 * * * *'

jobs:
  publish-docker:
    name: Build and Publish Docker Image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: mi2428/dotfiles
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_TOKEN }}
          registry: ghcr.io
          snapshot: true
          tags: "latest"
