# vim: ft=tmux
if -F '#{==:#{@theme},catppuccin-latte}' "source-file $HOME/dotfiles/etc/tmux/tmux/themes/catppuccin-latte-statusbar.conf"
if -F '#{==:#{@theme},catppuccin-frappe}' "source-file $HOME/dotfiles/etc/tmux/tmux/themes/catppuccin-frappe-statusbar.conf"
if -F '#{==:#{@theme},catppuccin-macchiato}' "source-file $HOME/dotfiles/etc/tmux/tmux/themes/catppuccin-macchiato-statusbar.conf"
if -F '#{==:#{@theme},catppuccin-mocha}' "source-file $HOME/dotfiles/etc/tmux/tmux/themes/catppuccin-mocha-statusbar.conf"
